name=RSHC_Utilities
version=0.2.0
author=Dale Weber
maintainer=Dale Weber <hybotix@hybridrobotix.com>
sentence=Utility Functions for the Robot Smart Home Controller (RSHC)
paragraph=These are utility functions for the RSHC. They are used to print values
and debug code.
category=Printing
url=http://example.com/
architectures=*
