name=RSHC_Print
version=1.0.0
author=Dale Weber
maintainer=Dale Weber <hybotix@hybridrobotix.io>
sentence=Print and Formatting functions.
paragraph=Provides print and formatting services for the robot.
category=Other
url=https://github.com/hybotix/RHSC_Print
architectures=*
depends=