name=Sensor Communication Library
version=0.4.0
author=IoThingsWare  <http://www.iothingsware.com>
maintainer=Toni Cafiero <tcafiero@iothingsware.com>
sentence=Arduino library for easy sensors data communication
paragraph=This library allow you to send filtered (mobile average) sensors data as a streeam of data in csv format.
category=Communication
url=https://github.com/tcafiero/SensorCommunicationLib
architectures=*
